-- DDL for generation_tasks table (unified task management)
CREATE TABLE IF NOT EXISTS generation_tasks (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    task_id         VARCHAR(64) NOT NULL,
    task_type       VARCHAR(32) NOT NULL,
    category        VARCHAR(20) NOT NULL DEFAULT 'local',
    provider        VARCHAR(20) DEFAULT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'queued',
    progress        FLOAT NOT NULL DEFAULT 0.0,
    error_message   TEXT DEFAULT NULL,
    prompt          TEXT DEFAULT NULL,
    model           VARCHAR(32) DEFAULT NULL,
    params_json     JSON DEFAULT NULL,
    result_url      VARCHAR(1024) DEFAULT NULL,
    thumbnail_url   VARCHAR(1024) DEFAULT NULL,
    extra_urls      JSON DEFAULT NULL,
    parent_task_id  VARCHAR(64) DEFAULT NULL,
    chain_id        VARCHAR(64) DEFAULT NULL,
    external_task_id VARCHAR(128) DEFAULT NULL,
    created_at      DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    started_at      DATETIME(3) DEFAULT NULL,
    completed_at    DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uk_task_id (task_id),
    INDEX idx_status (status),
    INDEX idx_category (category),
    INDEX idx_task_type (task_type),
    INDEX idx_created_at (created_at),
    INDEX idx_chain_id (chain_id),
    INDEX idx_external_task_id (external_task_id),
    INDEX idx_category_status_created (category, status, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
